[package]
name = "angryier-execution"
version.workspace = true
edition.workspace = true
license.workspace = true
description = "Execution plane contracts"

[dependencies]
angryier-types = { path = "../angryier-types" }
angryier-ir = { path = "../angryier-ir" }
angryier-expr = { path = "../angryier-expr" }
angryier-memory = { path = "../angryier-memory" }
angryier-state = { path = "../angryier-state" }

[lints]
workspace = true
