//! Diagnostic test: Instruction-form coverage census across PE test images.
//!
//! Sweeps PE test drivers from fixture directories and identifies XED
//! instruction classes that map to form 0 (unmapped / unsupported by semantic corpus).
//!
//! Outputs a ranked Markdown gap report to `/tmp/corpus_form_gaps.md`.
#![cfg(feature = "xed")]

use std::collections::{BTreeMap, BTreeSet};
use std::fmt::Write as FmtWrite;
use std::fs::File;
use std::io::Write as IoWrite;
use std::path::{Path, PathBuf};

use angryier_arch::Decoder;
use angryier_memory::{ByteValue, LayeredMemory};
use angryier_runtime::Runtime;
use angryier_types::{SemanticVersion, TargetProfileId};

static XED_ICLASS_NAMES: [&str; 1860] = [
    "INVALID",
    "AAA",
    "AAD",
    "AADD",
    "AAM",
    "AAND",
    "AAS",
    "ADC",
    "ADCX",
    "ADC_LOCK",
    "ADD",
    "ADDPD",
    "ADDPS",
    "ADDSD",
    "ADDSS",
    "ADDSUBPD",
    "ADDSUBPS",
    "ADD_LOCK",
    "ADOX",
    "AESDEC",
    "AESDEC128KL",
    "AESDEC256KL",
    "AESDECLAST",
    "AESDECWIDE128KL",
    "AESDECWIDE256KL",
    "AESENC",
    "AESENC128KL",
    "AESENC256KL",
    "AESENCLAST",
    "AESENCWIDE128KL",
    "AESENCWIDE256KL",
    "AESIMC",
    "AESKEYGENASSIST",
    "AND",
    "ANDN",
    "ANDNPD",
    "ANDNPS",
    "ANDPD",
    "ANDPS",
    "AND_LOCK",
    "AOR",
    "ARPL",
    "AXOR",
    "BEXTR",
    "BEXTR_XOP",
    "BLCFILL",
    "BLCI",
    "BLCIC",
    "BLCMSK",
    "BLCS",
    "BLENDPD",
    "BLENDPS",
    "BLENDVPD",
    "BLENDVPS",
    "BLSFILL",
    "BLSI",
    "BLSIC",
    "BLSMSK",
    "BLSR",
    "BNDCL",
    "BNDCN",
    "BNDCU",
    "BNDLDX",
    "BNDMK",
    "BNDMOV",
    "BNDSTX",
    "BOUND",
    "BSF",
    "BSR",
    "BSWAP",
    "BT",
    "BTC",
    "BTC_LOCK",
    "BTR",
    "BTR_LOCK",
    "BTS",
    "BTS_LOCK",
    "BZHI",
    "CALL_FAR",
    "CALL_NEAR",
    "CBW",
    "CCMPB",
    "CCMPBE",
    "CCMPF",
    "CCMPL",
    "CCMPLE",
    "CCMPNB",
    "CCMPNBE",
    "CCMPNL",
    "CCMPNLE",
    "CCMPNO",
    "CCMPNS",
    "CCMPNZ",
    "CCMPO",
    "CCMPS",
    "CCMPT",
    "CCMPZ",
    "CDQ",
    "CDQE",
    "CFCMOVB",
    "CFCMOVBE",
    "CFCMOVL",
    "CFCMOVLE",
    "CFCMOVNB",
    "CFCMOVNBE",
    "CFCMOVNL",
    "CFCMOVNLE",
    "CFCMOVNO",
    "CFCMOVNP",
    "CFCMOVNS",
    "CFCMOVNZ",
    "CFCMOVO",
    "CFCMOVP",
    "CFCMOVS",
    "CFCMOVZ",
    "CLAC",
    "CLC",
    "CLD",
    "CLDEMOTE",
    "CLFLUSH",
    "CLFLUSHOPT",
    "CLGI",
    "CLI",
    "CLRSSBSY",
    "CLTS",
    "CLUI",
    "CLWB",
    "CLZERO",
    "CMC",
    "CMOVB",
    "CMOVBE",
    "CMOVL",
    "CMOVLE",
    "CMOVNB",
    "CMOVNBE",
    "CMOVNL",
    "CMOVNLE",
    "CMOVNO",
    "CMOVNP",
    "CMOVNS",
    "CMOVNZ",
    "CMOVO",
    "CMOVP",
    "CMOVS",
    "CMOVZ",
    "CMP",
    "CMPBEXADD",
    "CMPBXADD",
    "CMPLEXADD",
    "CMPLXADD",
    "CMPNBEXADD",
    "CMPNBXADD",
    "CMPNLEXADD",
    "CMPNLXADD",
    "CMPNOXADD",
    "CMPNPXADD",
    "CMPNSXADD",
    "CMPNZXADD",
    "CMPOXADD",
    "CMPPD",
    "CMPPS",
    "CMPPXADD",
    "CMPSB",
    "CMPSD",
    "CMPSD_XMM",
    "CMPSQ",
    "CMPSS",
    "CMPSW",
    "CMPSXADD",
    "CMPXCHG",
    "CMPXCHG16B",
    "CMPXCHG16B_LOCK",
    "CMPXCHG8B",
    "CMPXCHG8B_LOCK",
    "CMPXCHG_LOCK",
    "CMPZXADD",
    "COMISD",
    "COMISS",
    "CPUID",
    "CQO",
    "CRC32",
    "CTESTB",
    "CTESTBE",
    "CTESTF",
    "CTESTL",
    "CTESTLE",
    "CTESTNB",
    "CTESTNBE",
    "CTESTNL",
    "CTESTNLE",
    "CTESTNO",
    "CTESTNS",
    "CTESTNZ",
    "CTESTO",
    "CTESTS",
    "CTESTT",
    "CTESTZ",
    "CVTDQ2PD",
    "CVTDQ2PS",
    "CVTPD2DQ",
    "CVTPD2PI",
    "CVTPD2PS",
    "CVTPI2PD",
    "CVTPI2PS",
    "CVTPS2DQ",
    "CVTPS2PD",
    "CVTPS2PI",
    "CVTSD2SI",
    "CVTSD2SS",
    "CVTSI2SD",
    "CVTSI2SS",
    "CVTSS2SD",
    "CVTSS2SI",
    "CVTTPD2DQ",
    "CVTTPD2PI",
    "CVTTPS2DQ",
    "CVTTPS2PI",
    "CVTTSD2SI",
    "CVTTSS2SI",
    "CWD",
    "CWDE",
    "DAA",
    "DAS",
    "DEC",
    "DEC_LOCK",
    "DIV",
    "DIVPD",
    "DIVPS",
    "DIVSD",
    "DIVSS",
    "DPPD",
    "DPPS",
    "EMMS",
    "ENCLS",
    "ENCLU",
    "ENCLV",
    "ENCODEKEY128",
    "ENCODEKEY256",
    "ENDBR32",
    "ENDBR64",
    "ENQCMD",
    "ENQCMDS",
    "ENTER",
    "ERETS",
    "ERETU",
    "EXTRACTPS",
    "EXTRQ",
    "F2XM1",
    "FABS",
    "FADD",
    "FADDP",
    "FBLD",
    "FBSTP",
    "FCHS",
    "FCMOVB",
    "FCMOVBE",
    "FCMOVE",
    "FCMOVNB",
    "FCMOVNBE",
    "FCMOVNE",
    "FCMOVNU",
    "FCMOVU",
    "FCOM",
    "FCOMI",
    "FCOMIP",
    "FCOMP",
    "FCOMPP",
    "FCOS",
    "FDECSTP",
    "FDISI8087_NOP",
    "FDIV",
    "FDIVP",
    "FDIVR",
    "FDIVRP",
    "FEMMS",
    "FENI8087_NOP",
    "FFREE",
    "FFREEP",
    "FIADD",
    "FICOM",
    "FICOMP",
    "FIDIV",
    "FIDIVR",
    "FILD",
    "FIMUL",
    "FINCSTP",
    "FIST",
    "FISTP",
    "FISTTP",
    "FISUB",
    "FISUBR",
    "FLD",
    "FLD1",
    "FLDCW",
    "FLDENV",
    "FLDL2E",
    "FLDL2T",
    "FLDLG2",
    "FLDLN2",
    "FLDPI",
    "FLDZ",
    "FMUL",
    "FMULP",
    "FNCLEX",
    "FNINIT",
    "FNOP",
    "FNSAVE",
    "FNSTCW",
    "FNSTENV",
    "FNSTSW",
    "FPATAN",
    "FPREM",
    "FPREM1",
    "FPTAN",
    "FRNDINT",
    "FRSTOR",
    "FSCALE",
    "FSETPM287_NOP",
    "FSIN",
    "FSINCOS",
    "FSQRT",
    "FST",
    "FSTP",
    "FSTPNCE",
    "FSUB",
    "FSUBP",
    "FSUBR",
    "FSUBRP",
    "FTST",
    "FUCOM",
    "FUCOMI",
    "FUCOMIP",
    "FUCOMP",
    "FUCOMPP",
    "FWAIT",
    "FXAM",
    "FXCH",
    "FXRSTOR",
    "FXRSTOR64",
    "FXSAVE",
    "FXSAVE64",
    "FXTRACT",
    "FYL2X",
    "FYL2XP1",
    "GETSEC",
    "GF2P8AFFINEINVQB",
    "GF2P8AFFINEQB",
    "GF2P8MULB",
    "HADDPD",
    "HADDPS",
    "HLT",
    "HRESET",
    "HSUBPD",
    "HSUBPS",
    "IDIV",
    "IMUL",
    "IN",
    "INC",
    "INCSSPD",
    "INCSSPQ",
    "INC_LOCK",
    "INSB",
    "INSD",
    "INSERTPS",
    "INSERTQ",
    "INSW",
    "INT",
    "INT1",
    "INT3",
    "INTO",
    "INVD",
    "INVEPT",
    "INVLPG",
    "INVLPGA",
    "INVLPGB",
    "INVPCID",
    "INVVPID",
    "IRET",
    "IRETD",
    "IRETQ",
    "JB",
    "JBE",
    "JCXZ",
    "JECXZ",
    "JL",
    "JLE",
    "JMP",
    "JMPABS",
    "JMP_FAR",
    "JNB",
    "JNBE",
    "JNL",
    "JNLE",
    "JNO",
    "JNP",
    "JNS",
    "JNZ",
    "JO",
    "JP",
    "JRCXZ",
    "JS",
    "JZ",
    "KADDB",
    "KADDD",
    "KADDQ",
    "KADDW",
    "KANDB",
    "KANDD",
    "KANDNB",
    "KANDND",
    "KANDNQ",
    "KANDNW",
    "KANDQ",
    "KANDW",
    "KMOVB",
    "KMOVD",
    "KMOVQ",
    "KMOVW",
    "KNOTB",
    "KNOTD",
    "KNOTQ",
    "KNOTW",
    "KORB",
    "KORD",
    "KORQ",
    "KORTESTB",
    "KORTESTD",
    "KORTESTQ",
    "KORTESTW",
    "KORW",
    "KSHIFTLB",
    "KSHIFTLD",
    "KSHIFTLQ",
    "KSHIFTLW",
    "KSHIFTRB",
    "KSHIFTRD",
    "KSHIFTRQ",
    "KSHIFTRW",
    "KTESTB",
    "KTESTD",
    "KTESTQ",
    "KTESTW",
    "KUNPCKBW",
    "KUNPCKDQ",
    "KUNPCKWD",
    "KXNORB",
    "KXNORD",
    "KXNORQ",
    "KXNORW",
    "KXORB",
    "KXORD",
    "KXORQ",
    "KXORW",
    "LAHF",
    "LAR",
    "LDDQU",
    "LDMXCSR",
    "LDS",
    "LDTILECFG",
    "LEA",
    "LEAVE",
    "LES",
    "LFENCE",
    "LFS",
    "LGDT",
    "LGS",
    "LIDT",
    "LKGS",
    "LLDT",
    "LLWPCB",
    "LMSW",
    "LOADIWKEY",
    "LODSB",
    "LODSD",
    "LODSQ",
    "LODSW",
    "LOOP",
    "LOOPE",
    "LOOPNE",
    "LSL",
    "LSS",
    "LTR",
    "LWPINS",
    "LWPVAL",
    "LZCNT",
    "MASKMOVDQU",
    "MASKMOVQ",
    "MAXPD",
    "MAXPS",
    "MAXSD",
    "MAXSS",
    "MCOMMIT",
    "MFENCE",
    "MINPD",
    "MINPS",
    "MINSD",
    "MINSS",
    "MONITOR",
    "MONITORX",
    "MOV",
    "MOVAPD",
    "MOVAPS",
    "MOVBE",
    "MOVD",
    "MOVDDUP",
    "MOVDIR64B",
    "MOVDIRI",
    "MOVDQ2Q",
    "MOVDQA",
    "MOVDQU",
    "MOVHLPS",
    "MOVHPD",
    "MOVHPS",
    "MOVLHPS",
    "MOVLPD",
    "MOVLPS",
    "MOVMSKPD",
    "MOVMSKPS",
    "MOVNTDQ",
    "MOVNTDQA",
    "MOVNTI",
    "MOVNTPD",
    "MOVNTPS",
    "MOVNTQ",
    "MOVNTSD",
    "MOVNTSS",
    "MOVQ",
    "MOVQ2DQ",
    "MOVSB",
    "MOVSD",
    "MOVSD_XMM",
    "MOVSHDUP",
    "MOVSLDUP",
    "MOVSQ",
    "MOVSS",
    "MOVSW",
    "MOVSX",
    "MOVSXD",
    "MOVUPD",
    "MOVUPS",
    "MOVZX",
    "MOV_CR",
    "MOV_DR",
    "MPSADBW",
    "MUL",
    "MULPD",
    "MULPS",
    "MULSD",
    "MULSS",
    "MULX",
    "MWAIT",
    "MWAITX",
    "NEG",
    "NEG_LOCK",
    "NOP",
    "NOP2",
    "NOP3",
    "NOP4",
    "NOP5",
    "NOP6",
    "NOP7",
    "NOP8",
    "NOP9",
    "NOT",
    "NOT_LOCK",
    "OR",
    "ORPD",
    "ORPS",
    "OR_LOCK",
    "OUT",
    "OUTSB",
    "OUTSD",
    "OUTSW",
    "PABSB",
    "PABSD",
    "PABSW",
    "PACKSSDW",
    "PACKSSWB",
    "PACKUSDW",
    "PACKUSWB",
    "PADDB",
    "PADDD",
    "PADDQ",
    "PADDSB",
    "PADDSW",
    "PADDUSB",
    "PADDUSW",
    "PADDW",
    "PALIGNR",
    "PAND",
    "PANDN",
    "PAUSE",
    "PAVGB",
    "PAVGUSB",
    "PAVGW",
    "PBLENDVB",
    "PBLENDW",
    "PBNDKB",
    "PCLMULQDQ",
    "PCMPEQB",
    "PCMPEQD",
    "PCMPEQQ",
    "PCMPEQW",
    "PCMPESTRI",
    "PCMPESTRI64",
    "PCMPESTRM",
    "PCMPESTRM64",
    "PCMPGTB",
    "PCMPGTD",
    "PCMPGTQ",
    "PCMPGTW",
    "PCMPISTRI",
    "PCMPISTRI64",
    "PCMPISTRM",
    "PCONFIG",
    "PDEP",
    "PEXT",
    "PEXTRB",
    "PEXTRD",
    "PEXTRQ",
    "PEXTRW",
    "PEXTRW_SSE4",
    "PF2ID",
    "PF2IW",
    "PFACC",
    "PFADD",
    "PFCMPEQ",
    "PFCMPGE",
    "PFCMPGT",
    "PFMAX",
    "PFMIN",
    "PFMUL",
    "PFNACC",
    "PFPNACC",
    "PFRCP",
    "PFRCPIT1",
    "PFRCPIT2",
    "PFRSQIT1",
    "PFRSQRT",
    "PFSUB",
    "PFSUBR",
    "PHADDD",
    "PHADDSW",
    "PHADDW",
    "PHMINPOSUW",
    "PHSUBD",
    "PHSUBSW",
    "PHSUBW",
    "PI2FD",
    "PI2FW",
    "PINSRB",
    "PINSRD",
    "PINSRQ",
    "PINSRW",
    "PMADDUBSW",
    "PMADDWD",
    "PMAXSB",
    "PMAXSD",
    "PMAXSW",
    "PMAXUB",
    "PMAXUD",
    "PMAXUW",
    "PMINSB",
    "PMINSD",
    "PMINSW",
    "PMINUB",
    "PMINUD",
    "PMINUW",
    "PMOVMSKB",
    "PMOVSXBD",
    "PMOVSXBQ",
    "PMOVSXBW",
    "PMOVSXDQ",
    "PMOVSXWD",
    "PMOVSXWQ",
    "PMOVZXBD",
    "PMOVZXBQ",
    "PMOVZXBW",
    "PMOVZXDQ",
    "PMOVZXWD",
    "PMOVZXWQ",
    "PMULDQ",
    "PMULHRSW",
    "PMULHRW",
    "PMULHUW",
    "PMULHW",
    "PMULLD",
    "PMULLW",
    "PMULUDQ",
    "POP",
    "POP2",
    "POP2P",
    "POPA",
    "POPAD",
    "POPCNT",
    "POPF",
    "POPFD",
    "POPFQ",
    "POPP",
    "POR",
    "PREFETCHIT0",
    "PREFETCHIT1",
    "PREFETCHNTA",
    "PREFETCHT0",
    "PREFETCHT1",
    "PREFETCHT2",
    "PREFETCHW",
    "PREFETCHWT1",
    "PREFETCH_EXCLUSIVE",
    "PREFETCH_RESERVED",
    "PSADBW",
    "PSHUFB",
    "PSHUFD",
    "PSHUFHW",
    "PSHUFLW",
    "PSHUFW",
    "PSIGNB",
    "PSIGND",
    "PSIGNW",
    "PSLLD",
    "PSLLDQ",
    "PSLLQ",
    "PSLLW",
    "PSMASH",
    "PSRAD",
    "PSRAW",
    "PSRLD",
    "PSRLDQ",
    "PSRLQ",
    "PSRLW",
    "PSUBB",
    "PSUBD",
    "PSUBQ",
    "PSUBSB",
    "PSUBSW",
    "PSUBUSB",
    "PSUBUSW",
    "PSUBW",
    "PSWAPD",
    "PTEST",
    "PTWRITE",
    "PUNPCKHBW",
    "PUNPCKHDQ",
    "PUNPCKHQDQ",
    "PUNPCKHWD",
    "PUNPCKLBW",
    "PUNPCKLDQ",
    "PUNPCKLQDQ",
    "PUNPCKLWD",
    "PUSH",
    "PUSH2",
    "PUSH2P",
    "PUSHA",
    "PUSHAD",
    "PUSHF",
    "PUSHFD",
    "PUSHFQ",
    "PUSHP",
    "PVALIDATE",
    "PXOR",
    "RCL",
    "RCPPS",
    "RCPSS",
    "RCR",
    "RDFSBASE",
    "RDGSBASE",
    "RDMSR",
    "RDMSRLIST",
    "RDPID",
    "RDPKRU",
    "RDPMC",
    "RDPRU",
    "RDRAND",
    "RDSEED",
    "RDSSPD",
    "RDSSPQ",
    "RDTSC",
    "RDTSCP",
    "REPE_CMPSB",
    "REPE_CMPSD",
    "REPE_CMPSQ",
    "REPE_CMPSW",
    "REPE_SCASB",
    "REPE_SCASD",
    "REPE_SCASQ",
    "REPE_SCASW",
    "REPNE_CMPSB",
    "REPNE_CMPSD",
    "REPNE_CMPSQ",
    "REPNE_CMPSW",
    "REPNE_SCASB",
    "REPNE_SCASD",
    "REPNE_SCASQ",
    "REPNE_SCASW",
    "REP_INSB",
    "REP_INSD",
    "REP_INSW",
    "REP_LODSB",
    "REP_LODSD",
    "REP_LODSQ",
    "REP_LODSW",
    "REP_MONTMUL",
    "REP_MOVSB",
    "REP_MOVSD",
    "REP_MOVSQ",
    "REP_MOVSW",
    "REP_OUTSB",
    "REP_OUTSD",
    "REP_OUTSW",
    "REP_STOSB",
    "REP_STOSD",
    "REP_STOSQ",
    "REP_STOSW",
    "REP_XCRYPTCBC",
    "REP_XCRYPTCFB",
    "REP_XCRYPTCTR",
    "REP_XCRYPTECB",
    "REP_XCRYPTOFB",
    "REP_XSHA1",
    "REP_XSHA256",
    "REP_XSTORE",
    "RET_FAR",
    "RET_NEAR",
    "RMPADJUST",
    "RMPUPDATE",
    "ROL",
    "ROR",
    "RORX",
    "ROUNDPD",
    "ROUNDPS",
    "ROUNDSD",
    "ROUNDSS",
    "RSM",
    "RSQRTPS",
    "RSQRTSS",
    "RSTORSSP",
    "SAHF",
    "SALC",
    "SAR",
    "SARX",
    "SAVEPREVSSP",
    "SBB",
    "SBB_LOCK",
    "SCASB",
    "SCASD",
    "SCASQ",
    "SCASW",
    "SEAMCALL",
    "SEAMOPS",
    "SEAMRET",
    "SENDUIPI",
    "SERIALIZE",
    "SETB",
    "SETBE",
    "SETL",
    "SETLE",
    "SETNB",
    "SETNBE",
    "SETNL",
    "SETNLE",
    "SETNO",
    "SETNP",
    "SETNS",
    "SETNZ",
    "SETO",
    "SETP",
    "SETS",
    "SETSSBSY",
    "SETZ",
    "SFENCE",
    "SGDT",
    "SHA1MSG1",
    "SHA1MSG2",
    "SHA1NEXTE",
    "SHA1RNDS4",
    "SHA256MSG1",
    "SHA256MSG2",
    "SHA256RNDS2",
    "SHL",
    "SHLD",
    "SHLX",
    "SHR",
    "SHRD",
    "SHRX",
    "SHUFPD",
    "SHUFPS",
    "SIDT",
    "SKINIT",
    "SLDT",
    "SLWPCB",
    "SMSW",
    "SQRTPD",
    "SQRTPS",
    "SQRTSD",
    "SQRTSS",
    "STAC",
    "STC",
    "STD",
    "STGI",
    "STI",
    "STMXCSR",
    "STOSB",
    "STOSD",
    "STOSQ",
    "STOSW",
    "STR",
    "STTILECFG",
    "STUI",
    "SUB",
    "SUBPD",
    "SUBPS",
    "SUBSD",
    "SUBSS",
    "SUB_LOCK",
    "SWAPGS",
    "SYSCALL",
    "SYSCALL_32",
    "SYSENTER",
    "SYSEXIT",
    "SYSRET",
    "SYSRET64",
    "SYSRET_AMD",
    "T1MSKC",
    "TCMMIMFP16PS",
    "TCMMRLFP16PS",
    "TDCALL",
    "TDPBF16PS",
    "TDPBSSD",
    "TDPBSUD",
    "TDPBUSD",
    "TDPBUUD",
    "TDPFP16PS",
    "TEST",
    "TESTUI",
    "TILELOADD",
    "TILELOADDT1",
    "TILERELEASE",
    "TILESTORED",
    "TILEZERO",
    "TLBSYNC",
    "TPAUSE",
    "TZCNT",
    "TZMSK",
    "UCOMISD",
    "UCOMISS",
    "UD0",
    "UD1",
    "UD2",
    "UIRET",
    "UMONITOR",
    "UMWAIT",
    "UNPCKHPD",
    "UNPCKHPS",
    "UNPCKLPD",
    "UNPCKLPS",
    "URDMSR",
    "UWRMSR",
    "V4FMADDPS",
    "V4FMADDSS",
    "V4FNMADDPS",
    "V4FNMADDSS",
    "VADDPD",
    "VADDPH",
    "VADDPS",
    "VADDSD",
    "VADDSH",
    "VADDSS",
    "VADDSUBPD",
    "VADDSUBPS",
    "VAESDEC",
    "VAESDECLAST",
    "VAESENC",
    "VAESENCLAST",
    "VAESIMC",
    "VAESKEYGENASSIST",
    "VALIGND",
    "VALIGNQ",
    "VANDNPD",
    "VANDNPS",
    "VANDPD",
    "VANDPS",
    "VBCSTNEBF162PS",
    "VBCSTNESH2PS",
    "VBLENDMPD",
    "VBLENDMPS",
    "VBLENDPD",
    "VBLENDPS",
    "VBLENDVPD",
    "VBLENDVPS",
    "VBROADCASTF128",
    "VBROADCASTF32X2",
    "VBROADCASTF32X4",
    "VBROADCASTF32X8",
    "VBROADCASTF64X2",
    "VBROADCASTF64X4",
    "VBROADCASTI128",
    "VBROADCASTI32X2",
    "VBROADCASTI32X4",
    "VBROADCASTI32X8",
    "VBROADCASTI64X2",
    "VBROADCASTI64X4",
    "VBROADCASTSD",
    "VBROADCASTSS",
    "VCMPPD",
    "VCMPPH",
    "VCMPPS",
    "VCMPSD",
    "VCMPSH",
    "VCMPSS",
    "VCOMISD",
    "VCOMISH",
    "VCOMISS",
    "VCOMPRESSPD",
    "VCOMPRESSPS",
    "VCVTDQ2PD",
    "VCVTDQ2PH",
    "VCVTDQ2PS",
    "VCVTNE2PS2BF16",
    "VCVTNEEBF162PS",
    "VCVTNEEPH2PS",
    "VCVTNEOBF162PS",
    "VCVTNEOPH2PS",
    "VCVTNEPS2BF16",
    "VCVTPD2DQ",
    "VCVTPD2PH",
    "VCVTPD2PS",
    "VCVTPD2QQ",
    "VCVTPD2UDQ",
    "VCVTPD2UQQ",
    "VCVTPH2DQ",
    "VCVTPH2PD",
    "VCVTPH2PS",
    "VCVTPH2PSX",
    "VCVTPH2QQ",
    "VCVTPH2UDQ",
    "VCVTPH2UQQ",
    "VCVTPH2UW",
    "VCVTPH2W",
    "VCVTPS2DQ",
    "VCVTPS2PD",
    "VCVTPS2PH",
    "VCVTPS2PHX",
    "VCVTPS2QQ",
    "VCVTPS2UDQ",
    "VCVTPS2UQQ",
    "VCVTQQ2PD",
    "VCVTQQ2PH",
    "VCVTQQ2PS",
    "VCVTSD2SH",
    "VCVTSD2SI",
    "VCVTSD2SS",
    "VCVTSD2USI",
    "VCVTSH2SD",
    "VCVTSH2SI",
    "VCVTSH2SS",
    "VCVTSH2USI",
    "VCVTSI2SD",
    "VCVTSI2SH",
    "VCVTSI2SS",
    "VCVTSS2SD",
    "VCVTSS2SH",
    "VCVTSS2SI",
    "VCVTSS2USI",
    "VCVTTPD2DQ",
    "VCVTTPD2QQ",
    "VCVTTPD2UDQ",
    "VCVTTPD2UQQ",
    "VCVTTPH2DQ",
    "VCVTTPH2QQ",
    "VCVTTPH2UDQ",
    "VCVTTPH2UQQ",
    "VCVTTPH2UW",
    "VCVTTPH2W",
    "VCVTTPS2DQ",
    "VCVTTPS2QQ",
    "VCVTTPS2UDQ",
    "VCVTTPS2UQQ",
    "VCVTTSD2SI",
    "VCVTTSD2USI",
    "VCVTTSH2SI",
    "VCVTTSH2USI",
    "VCVTTSS2SI",
    "VCVTTSS2USI",
    "VCVTUDQ2PD",
    "VCVTUDQ2PH",
    "VCVTUDQ2PS",
    "VCVTUQQ2PD",
    "VCVTUQQ2PH",
    "VCVTUQQ2PS",
    "VCVTUSI2SD",
    "VCVTUSI2SH",
    "VCVTUSI2SS",
    "VCVTUW2PH",
    "VCVTW2PH",
    "VDBPSADBW",
    "VDIVPD",
    "VDIVPH",
    "VDIVPS",
    "VDIVSD",
    "VDIVSH",
    "VDIVSS",
    "VDPBF16PS",
    "VDPPD",
    "VDPPS",
    "VERR",
    "VERW",
    "VEXP2PD",
    "VEXP2PS",
    "VEXPANDPD",
    "VEXPANDPS",
    "VEXTRACTF128",
    "VEXTRACTF32X4",
    "VEXTRACTF32X8",
    "VEXTRACTF64X2",
    "VEXTRACTF64X4",
    "VEXTRACTI128",
    "VEXTRACTI32X4",
    "VEXTRACTI32X8",
    "VEXTRACTI64X2",
    "VEXTRACTI64X4",
    "VEXTRACTPS",
    "VFCMADDCPH",
    "VFCMADDCSH",
    "VFCMULCPH",
    "VFCMULCSH",
    "VFIXUPIMMPD",
    "VFIXUPIMMPS",
    "VFIXUPIMMSD",
    "VFIXUPIMMSS",
    "VFMADD132PD",
    "VFMADD132PH",
    "VFMADD132PS",
    "VFMADD132SD",
    "VFMADD132SH",
    "VFMADD132SS",
    "VFMADD213PD",
    "VFMADD213PH",
    "VFMADD213PS",
    "VFMADD213SD",
    "VFMADD213SH",
    "VFMADD213SS",
    "VFMADD231PD",
    "VFMADD231PH",
    "VFMADD231PS",
    "VFMADD231SD",
    "VFMADD231SH",
    "VFMADD231SS",
    "VFMADDCPH",
    "VFMADDCSH",
    "VFMADDPD",
    "VFMADDPS",
    "VFMADDSD",
    "VFMADDSS",
    "VFMADDSUB132PD",
    "VFMADDSUB132PH",
    "VFMADDSUB132PS",
    "VFMADDSUB213PD",
    "VFMADDSUB213PH",
    "VFMADDSUB213PS",
    "VFMADDSUB231PD",
    "VFMADDSUB231PH",
    "VFMADDSUB231PS",
    "VFMADDSUBPD",
    "VFMADDSUBPS",
    "VFMSUB132PD",
    "VFMSUB132PH",
    "VFMSUB132PS",
    "VFMSUB132SD",
    "VFMSUB132SH",
    "VFMSUB132SS",
    "VFMSUB213PD",
    "VFMSUB213PH",
    "VFMSUB213PS",
    "VFMSUB213SD",
    "VFMSUB213SH",
    "VFMSUB213SS",
    "VFMSUB231PD",
    "VFMSUB231PH",
    "VFMSUB231PS",
    "VFMSUB231SD",
    "VFMSUB231SH",
    "VFMSUB231SS",
    "VFMSUBADD132PD",
    "VFMSUBADD132PH",
    "VFMSUBADD132PS",
    "VFMSUBADD213PD",
    "VFMSUBADD213PH",
    "VFMSUBADD213PS",
    "VFMSUBADD231PD",
    "VFMSUBADD231PH",
    "VFMSUBADD231PS",
    "VFMSUBADDPD",
    "VFMSUBADDPS",
    "VFMSUBPD",
    "VFMSUBPS",
    "VFMSUBSD",
    "VFMSUBSS",
    "VFMULCPH",
    "VFMULCSH",
    "VFNMADD132PD",
    "VFNMADD132PH",
    "VFNMADD132PS",
    "VFNMADD132SD",
    "VFNMADD132SH",
    "VFNMADD132SS",
    "VFNMADD213PD",
    "VFNMADD213PH",
    "VFNMADD213PS",
    "VFNMADD213SD",
    "VFNMADD213SH",
    "VFNMADD213SS",
    "VFNMADD231PD",
    "VFNMADD231PH",
    "VFNMADD231PS",
    "VFNMADD231SD",
    "VFNMADD231SH",
    "VFNMADD231SS",
    "VFNMADDPD",
    "VFNMADDPS",
    "VFNMADDSD",
    "VFNMADDSS",
    "VFNMSUB132PD",
    "VFNMSUB132PH",
    "VFNMSUB132PS",
    "VFNMSUB132SD",
    "VFNMSUB132SH",
    "VFNMSUB132SS",
    "VFNMSUB213PD",
    "VFNMSUB213PH",
    "VFNMSUB213PS",
    "VFNMSUB213SD",
    "VFNMSUB213SH",
    "VFNMSUB213SS",
    "VFNMSUB231PD",
    "VFNMSUB231PH",
    "VFNMSUB231PS",
    "VFNMSUB231SD",
    "VFNMSUB231SH",
    "VFNMSUB231SS",
    "VFNMSUBPD",
    "VFNMSUBPS",
    "VFNMSUBSD",
    "VFNMSUBSS",
    "VFPCLASSPD",
    "VFPCLASSPH",
    "VFPCLASSPS",
    "VFPCLASSSD",
    "VFPCLASSSH",
    "VFPCLASSSS",
    "VFRCZPD",
    "VFRCZPS",
    "VFRCZSD",
    "VFRCZSS",
    "VGATHERDPD",
    "VGATHERDPS",
    "VGATHERPF0DPD",
    "VGATHERPF0DPS",
    "VGATHERPF0QPD",
    "VGATHERPF0QPS",
    "VGATHERPF1DPD",
    "VGATHERPF1DPS",
    "VGATHERPF1QPD",
    "VGATHERPF1QPS",
    "VGATHERQPD",
    "VGATHERQPS",
    "VGETEXPPD",
    "VGETEXPPH",
    "VGETEXPPS",
    "VGETEXPSD",
    "VGETEXPSH",
    "VGETEXPSS",
    "VGETMANTPD",
    "VGETMANTPH",
    "VGETMANTPS",
    "VGETMANTSD",
    "VGETMANTSH",
    "VGETMANTSS",
    "VGF2P8AFFINEINVQB",
    "VGF2P8AFFINEQB",
    "VGF2P8MULB",
    "VHADDPD",
    "VHADDPS",
    "VHSUBPD",
    "VHSUBPS",
    "VINSERTF128",
    "VINSERTF32X4",
    "VINSERTF32X8",
    "VINSERTF64X2",
    "VINSERTF64X4",
    "VINSERTI128",
    "VINSERTI32X4",
    "VINSERTI32X8",
    "VINSERTI64X2",
    "VINSERTI64X4",
    "VINSERTPS",
    "VLDDQU",
    "VLDMXCSR",
    "VMASKMOVDQU",
    "VMASKMOVPD",
    "VMASKMOVPS",
    "VMAXPD",
    "VMAXPH",
    "VMAXPS",
    "VMAXSD",
    "VMAXSH",
    "VMAXSS",
    "VMCALL",
    "VMCLEAR",
    "VMFUNC",
    "VMINPD",
    "VMINPH",
    "VMINPS",
    "VMINSD",
    "VMINSH",
    "VMINSS",
    "VMLAUNCH",
    "VMLOAD",
    "VMMCALL",
    "VMOVAPD",
    "VMOVAPS",
    "VMOVD",
    "VMOVDDUP",
    "VMOVDQA",
    "VMOVDQA32",
    "VMOVDQA64",
    "VMOVDQU",
    "VMOVDQU16",
    "VMOVDQU32",
    "VMOVDQU64",
    "VMOVDQU8",
    "VMOVHLPS",
    "VMOVHPD",
    "VMOVHPS",
    "VMOVLHPS",
    "VMOVLPD",
    "VMOVLPS",
    "VMOVMSKPD",
    "VMOVMSKPS",
    "VMOVNTDQ",
    "VMOVNTDQA",
    "VMOVNTPD",
    "VMOVNTPS",
    "VMOVQ",
    "VMOVSD",
    "VMOVSH",
    "VMOVSHDUP",
    "VMOVSLDUP",
    "VMOVSS",
    "VMOVUPD",
    "VMOVUPS",
    "VMOVW",
    "VMPSADBW",
    "VMPTRLD",
    "VMPTRST",
    "VMREAD",
    "VMRESUME",
    "VMRUN",
    "VMSAVE",
    "VMULPD",
    "VMULPH",
    "VMULPS",
    "VMULSD",
    "VMULSH",
    "VMULSS",
    "VMWRITE",
    "VMXOFF",
    "VMXON",
    "VORPD",
    "VORPS",
    "VP2INTERSECTD",
    "VP2INTERSECTQ",
    "VP4DPWSSD",
    "VP4DPWSSDS",
    "VPABSB",
    "VPABSD",
    "VPABSQ",
    "VPABSW",
    "VPACKSSDW",
    "VPACKSSWB",
    "VPACKUSDW",
    "VPACKUSWB",
    "VPADDB",
    "VPADDD",
    "VPADDQ",
    "VPADDSB",
    "VPADDSW",
    "VPADDUSB",
    "VPADDUSW",
    "VPADDW",
    "VPALIGNR",
    "VPAND",
    "VPANDD",
    "VPANDN",
    "VPANDND",
    "VPANDNQ",
    "VPANDQ",
    "VPAVGB",
    "VPAVGW",
    "VPBLENDD",
    "VPBLENDMB",
    "VPBLENDMD",
    "VPBLENDMQ",
    "VPBLENDMW",
    "VPBLENDVB",
    "VPBLENDW",
    "VPBROADCASTB",
    "VPBROADCASTD",
    "VPBROADCASTMB2Q",
    "VPBROADCASTMW2D",
    "VPBROADCASTQ",
    "VPBROADCASTW",
    "VPCLMULQDQ",
    "VPCMOV",
    "VPCMPB",
    "VPCMPD",
    "VPCMPEQB",
    "VPCMPEQD",
    "VPCMPEQQ",
    "VPCMPEQW",
    "VPCMPESTRI",
    "VPCMPESTRI64",
    "VPCMPESTRM",
    "VPCMPESTRM64",
    "VPCMPGTB",
    "VPCMPGTD",
    "VPCMPGTQ",
    "VPCMPGTW",
    "VPCMPISTRI",
    "VPCMPISTRI64",
    "VPCMPISTRM",
    "VPCMPQ",
    "VPCMPUB",
    "VPCMPUD",
    "VPCMPUQ",
    "VPCMPUW",
    "VPCMPW",
    "VPCOMB",
    "VPCOMD",
    "VPCOMPRESSB",
    "VPCOMPRESSD",
    "VPCOMPRESSQ",
    "VPCOMPRESSW",
    "VPCOMQ",
    "VPCOMUB",
    "VPCOMUD",
    "VPCOMUQ",
    "VPCOMUW",
    "VPCOMW",
    "VPCONFLICTD",
    "VPCONFLICTQ",
    "VPDPBSSD",
    "VPDPBSSDS",
    "VPDPBSUD",
    "VPDPBSUDS",
    "VPDPBUSD",
    "VPDPBUSDS",
    "VPDPBUUD",
    "VPDPBUUDS",
    "VPDPWSSD",
    "VPDPWSSDS",
    "VPDPWSUD",
    "VPDPWSUDS",
    "VPDPWUSD",
    "VPDPWUSDS",
    "VPDPWUUD",
    "VPDPWUUDS",
    "VPERM2F128",
    "VPERM2I128",
    "VPERMB",
    "VPERMD",
    "VPERMI2B",
    "VPERMI2D",
    "VPERMI2PD",
    "VPERMI2PS",
    "VPERMI2Q",
    "VPERMI2W",
    "VPERMIL2PD",
    "VPERMIL2PS",
    "VPERMILPD",
    "VPERMILPS",
    "VPERMPD",
    "VPERMPS",
    "VPERMQ",
    "VPERMT2B",
    "VPERMT2D",
    "VPERMT2PD",
    "VPERMT2PS",
    "VPERMT2Q",
    "VPERMT2W",
    "VPERMW",
    "VPEXPANDB",
    "VPEXPANDD",
    "VPEXPANDQ",
    "VPEXPANDW",
    "VPEXTRB",
    "VPEXTRD",
    "VPEXTRQ",
    "VPEXTRW",
    "VPEXTRW_C5",
    "VPGATHERDD",
    "VPGATHERDQ",
    "VPGATHERQD",
    "VPGATHERQQ",
    "VPHADDBD",
    "VPHADDBQ",
    "VPHADDBW",
    "VPHADDD",
    "VPHADDDQ",
    "VPHADDSW",
    "VPHADDUBD",
    "VPHADDUBQ",
    "VPHADDUBW",
    "VPHADDUDQ",
    "VPHADDUWD",
    "VPHADDUWQ",
    "VPHADDW",
    "VPHADDWD",
    "VPHADDWQ",
    "VPHMINPOSUW",
    "VPHSUBBW",
    "VPHSUBD",
    "VPHSUBDQ",
    "VPHSUBSW",
    "VPHSUBW",
    "VPHSUBWD",
    "VPINSRB",
    "VPINSRD",
    "VPINSRQ",
    "VPINSRW",
    "VPLZCNTD",
    "VPLZCNTQ",
    "VPMACSDD",
    "VPMACSDQH",
    "VPMACSDQL",
    "VPMACSSDD",
    "VPMACSSDQH",
    "VPMACSSDQL",
    "VPMACSSWD",
    "VPMACSSWW",
    "VPMACSWD",
    "VPMACSWW",
    "VPMADCSSWD",
    "VPMADCSWD",
    "VPMADD52HUQ",
    "VPMADD52LUQ",
    "VPMADDUBSW",
    "VPMADDWD",
    "VPMASKMOVD",
    "VPMASKMOVQ",
    "VPMAXSB",
    "VPMAXSD",
    "VPMAXSQ",
    "VPMAXSW",
    "VPMAXUB",
    "VPMAXUD",
    "VPMAXUQ",
    "VPMAXUW",
    "VPMINSB",
    "VPMINSD",
    "VPMINSQ",
    "VPMINSW",
    "VPMINUB",
    "VPMINUD",
    "VPMINUQ",
    "VPMINUW",
    "VPMOVB2M",
    "VPMOVD2M",
    "VPMOVDB",
    "VPMOVDW",
    "VPMOVM2B",
    "VPMOVM2D",
    "VPMOVM2Q",
    "VPMOVM2W",
    "VPMOVMSKB",
    "VPMOVQ2M",
    "VPMOVQB",
    "VPMOVQD",
    "VPMOVQW",
    "VPMOVSDB",
    "VPMOVSDW",
    "VPMOVSQB",
    "VPMOVSQD",
    "VPMOVSQW",
    "VPMOVSWB",
    "VPMOVSXBD",
    "VPMOVSXBQ",
    "VPMOVSXBW",
    "VPMOVSXDQ",
    "VPMOVSXWD",
    "VPMOVSXWQ",
    "VPMOVUSDB",
    "VPMOVUSDW",
    "VPMOVUSQB",
    "VPMOVUSQD",
    "VPMOVUSQW",
    "VPMOVUSWB",
    "VPMOVW2M",
    "VPMOVWB",
    "VPMOVZXBD",
    "VPMOVZXBQ",
    "VPMOVZXBW",
    "VPMOVZXDQ",
    "VPMOVZXWD",
    "VPMOVZXWQ",
    "VPMULDQ",
    "VPMULHRSW",
    "VPMULHUW",
    "VPMULHW",
    "VPMULLD",
    "VPMULLQ",
    "VPMULLW",
    "VPMULTISHIFTQB",
    "VPMULUDQ",
    "VPOPCNTB",
    "VPOPCNTD",
    "VPOPCNTQ",
    "VPOPCNTW",
    "VPOR",
    "VPORD",
    "VPORQ",
    "VPPERM",
    "VPROLD",
    "VPROLQ",
    "VPROLVD",
    "VPROLVQ",
    "VPRORD",
    "VPRORQ",
    "VPRORVD",
    "VPRORVQ",
    "VPROTB",
    "VPROTD",
    "VPROTQ",
    "VPROTW",
    "VPSADBW",
    "VPSCATTERDD",
    "VPSCATTERDQ",
    "VPSCATTERQD",
    "VPSCATTERQQ",
    "VPSHAB",
    "VPSHAD",
    "VPSHAQ",
    "VPSHAW",
    "VPSHLB",
    "VPSHLD",
    "VPSHLDD",
    "VPSHLDQ",
    "VPSHLDVD",
    "VPSHLDVQ",
    "VPSHLDVW",
    "VPSHLDW",
    "VPSHLQ",
    "VPSHLW",
    "VPSHRDD",
    "VPSHRDQ",
    "VPSHRDVD",
    "VPSHRDVQ",
    "VPSHRDVW",
    "VPSHRDW",
    "VPSHUFB",
    "VPSHUFBITQMB",
    "VPSHUFD",
    "VPSHUFHW",
    "VPSHUFLW",
    "VPSIGNB",
    "VPSIGND",
    "VPSIGNW",
    "VPSLLD",
    "VPSLLDQ",
    "VPSLLQ",
    "VPSLLVD",
    "VPSLLVQ",
    "VPSLLVW",
    "VPSLLW",
    "VPSRAD",
    "VPSRAQ",
    "VPSRAVD",
    "VPSRAVQ",
    "VPSRAVW",
    "VPSRAW",
    "VPSRLD",
    "VPSRLDQ",
    "VPSRLQ",
    "VPSRLVD",
    "VPSRLVQ",
    "VPSRLVW",
    "VPSRLW",
    "VPSUBB",
    "VPSUBD",
    "VPSUBQ",
    "VPSUBSB",
    "VPSUBSW",
    "VPSUBUSB",
    "VPSUBUSW",
    "VPSUBW",
    "VPTERNLOGD",
    "VPTERNLOGQ",
    "VPTEST",
    "VPTESTMB",
    "VPTESTMD",
    "VPTESTMQ",
    "VPTESTMW",
    "VPTESTNMB",
    "VPTESTNMD",
    "VPTESTNMQ",
    "VPTESTNMW",
    "VPUNPCKHBW",
    "VPUNPCKHDQ",
    "VPUNPCKHQDQ",
    "VPUNPCKHWD",
    "VPUNPCKLBW",
    "VPUNPCKLDQ",
    "VPUNPCKLQDQ",
    "VPUNPCKLWD",
    "VPXOR",
    "VPXORD",
    "VPXORQ",
    "VRANGEPD",
    "VRANGEPS",
    "VRANGESD",
    "VRANGESS",
    "VRCP14PD",
    "VRCP14PS",
    "VRCP14SD",
    "VRCP14SS",
    "VRCP28PD",
    "VRCP28PS",
    "VRCP28SD",
    "VRCP28SS",
    "VRCPPH",
    "VRCPPS",
    "VRCPSH",
    "VRCPSS",
    "VREDUCEPD",
    "VREDUCEPH",
    "VREDUCEPS",
    "VREDUCESD",
    "VREDUCESH",
    "VREDUCESS",
    "VRNDSCALEPD",
    "VRNDSCALEPH",
    "VRNDSCALEPS",
    "VRNDSCALESD",
    "VRNDSCALESH",
    "VRNDSCALESS",
    "VROUNDPD",
    "VROUNDPS",
    "VROUNDSD",
    "VROUNDSS",
    "VRSQRT14PD",
    "VRSQRT14PS",
    "VRSQRT14SD",
    "VRSQRT14SS",
    "VRSQRT28PD",
    "VRSQRT28PS",
    "VRSQRT28SD",
    "VRSQRT28SS",
    "VRSQRTPH",
    "VRSQRTPS",
    "VRSQRTSH",
    "VRSQRTSS",
    "VSCALEFPD",
    "VSCALEFPH",
    "VSCALEFPS",
    "VSCALEFSD",
    "VSCALEFSH",
    "VSCALEFSS",
    "VSCATTERDPD",
    "VSCATTERDPS",
    "VSCATTERPF0DPD",
    "VSCATTERPF0DPS",
    "VSCATTERPF0QPD",
    "VSCATTERPF0QPS",
    "VSCATTERPF1DPD",
    "VSCATTERPF1DPS",
    "VSCATTERPF1QPD",
    "VSCATTERPF1QPS",
    "VSCATTERQPD",
    "VSCATTERQPS",
    "VSHA512MSG1",
    "VSHA512MSG2",
    "VSHA512RNDS2",
    "VSHUFF32X4",
    "VSHUFF64X2",
    "VSHUFI32X4",
    "VSHUFI64X2",
    "VSHUFPD",
    "VSHUFPS",
    "VSM3MSG1",
    "VSM3MSG2",
    "VSM3RNDS2",
    "VSM4KEY4",
    "VSM4RNDS4",
    "VSQRTPD",
    "VSQRTPH",
    "VSQRTPS",
    "VSQRTSD",
    "VSQRTSH",
    "VSQRTSS",
    "VSTMXCSR",
    "VSUBPD",
    "VSUBPH",
    "VSUBPS",
    "VSUBSD",
    "VSUBSH",
    "VSUBSS",
    "VTESTPD",
    "VTESTPS",
    "VUCOMISD",
    "VUCOMISH",
    "VUCOMISS",
    "VUNPCKHPD",
    "VUNPCKHPS",
    "VUNPCKLPD",
    "VUNPCKLPS",
    "VXORPD",
    "VXORPS",
    "VZEROALL",
    "VZEROUPPER",
    "WBINVD",
    "WBNOINVD",
    "WRFSBASE",
    "WRGSBASE",
    "WRMSR",
    "WRMSRLIST",
    "WRMSRNS",
    "WRPKRU",
    "WRSSD",
    "WRSSQ",
    "WRUSSD",
    "WRUSSQ",
    "XABORT",
    "XADD",
    "XADD_LOCK",
    "XBEGIN",
    "XCHG",
    "XEND",
    "XGETBV",
    "XLAT",
    "XOR",
    "XORPD",
    "XORPS",
    "XOR_LOCK",
    "XRESLDTRK",
    "XRSTOR",
    "XRSTOR64",
    "XRSTORS",
    "XRSTORS64",
    "XSAVE",
    "XSAVE64",
    "XSAVEC",
    "XSAVEC64",
    "XSAVEOPT",
    "XSAVEOPT64",
    "XSAVES",
    "XSAVES64",
    "XSETBV",
    "XSTORE",
    "XSUSLDTRK",
    "XTEST",
    "LAST",
];

/// Per-image sweep result.
struct ImageSummary {
    name: String,
    total_swept: u64,
    unmapped_count: u64,
    unmapped_pct: f64,
    top3_unmapped: Vec<(u32, u64)>,
}

/// Global census data for one XED iclass.
struct IclassCensus {
    iclass_id: u32,
    total_count: u64,
    images_hit: BTreeSet<String>,
    example_addr: u64,
    example_bytes: Vec<u8>,
}

/// Read up to `len` concrete bytes at `addr` (symbolic bytes become 0xcc).
fn concrete_at(process: &angryier_runtime::Process, addr: u64, len: usize) -> Option<Vec<u8>> {
    let bytes = match process.state.memory.read(addr, len) {
        Ok(b) => b,
        Err(_) => return None,
    };
    Some(
        bytes
            .iter()
            .map(|b| match b {
                ByteValue::Concrete(v) => *v,
                ByteValue::Symbolic(_) => 0xcc,
            })
            .collect(),
    )
}

/// Resolves XED iclass id to mnemonic string.
fn xed_iclass_name(id: u32) -> &'static str {
    match XED_ICLASS_NAMES.get(id as usize) {
        Some(name) => name,
        None => "UNKNOWN",
    }
}

/// Collects fixture directories, resolving $HOME with graceful fallback.
fn fixture_dirs() -> Vec<PathBuf> {
    let home = match std::env::var("HOME") {
        Ok(h) => h,
        Err(_) => "/home/john".to_string(),
    };
    vec![
        PathBuf::from(&home).join("Documents/driver_analysis/drivers/sources/caledonia-drivers/bin-elastic"),
        PathBuf::from(&home).join("Documents/byovd-harness/ghidra_pipeline/fixtures/bin"),
    ]
}

/// Collects all regular files in a directory, sorted by path.
fn collect_image_files(dir: &Path) -> Vec<PathBuf> {
    let mut files = Vec::new();
    let entries = match std::fs::read_dir(dir) {
        Ok(e) => e,
        Err(_) => {
            eprintln!("SKIP fixture dir absent: {}", dir.display());
            return files;
        }
    };
    for entry in entries.flatten() {
        let path = entry.path();
        if path.is_file() {
            files.push(path);
        }
    }
    files.sort();
    files
}

#[test]
fn form_census() -> Result<(), Box<dyn std::error::Error>> {
    let mut all_files = Vec::new();
    for dir in &fixture_dirs() {
        all_files.extend(collect_image_files(dir));
    }
    all_files.sort();
    all_files.dedup();

    let raw_decoder = angryier_arch_xed_ffi::XedDecoder::new();
    let mut global_tallies: BTreeMap<u32, IclassCensus> = BTreeMap::new();
    let mut image_summaries: Vec<ImageSummary> = Vec::new();

    let mut total_processed: usize = 0;
    let mut total_skipped: usize = 0;

    for file_path in &all_files {
        total_processed += 1;
        let file_name = match file_path.file_name() {
            Some(name) => name.to_string_lossy().to_string(),
            None => file_path.display().to_string(),
        };

        let bytes = match std::fs::read(file_path) {
            Ok(b) => b,
            Err(_) => {
                eprintln!("SKIP {}: unreadable", file_name);
                total_skipped += 1;
                continue;
            }
        };

        let runtime = Runtime::with_native_xed(SemanticVersion(1), TargetProfileId(1));
        let process = match runtime.load_pe_driver(&bytes) {
            Ok(p) => p,
            Err(e) => {
                eprintln!("SKIP {}: load_pe_driver failed ({:?})", file_name, e);
                total_skipped += 1;
                continue;
            }
        };

        let entry: u64 = process.pc().unwrap_or_default();
        let start = entry.saturating_sub(0x2000);
        let end = entry.saturating_add(0x2000);

        let mut addr = start;
        while addr < entry && concrete_at(&process, addr, 1).is_none() {
            if addr.saturating_add(0x100) < entry && concrete_at(&process, addr.saturating_add(0x100), 1).is_none() {
                addr = addr.saturating_add(0x100);
            } else {
                addr = addr.saturating_add(1);
            }
        }

        let mut total_swept: u64 = 0;
        let mut unmapped_count: u64 = 0;
        let mut image_unmapped_iclasses: BTreeMap<u32, u64> = BTreeMap::new();

        for _ in 0..4096 {
            if addr >= end {
                break;
            }
            let Some(concrete) = concrete_at(&process, addr, 15) else {
                break;
            };
            let Ok(decoded) = runtime.decoder.decode(addr, &concrete) else {
                addr = addr.wrapping_add(1);
                continue;
            };
            let len = usize::from(decoded.length);
            if len == 0 {
                break;
            }
            total_swept += 1;

            if decoded.form_id == angryier_runtime::form_map::UNMAPPED_FORM_ID {
                unmapped_count += 1;
                let raw_iclass = match raw_decoder.decode(addr, &concrete) {
                    Ok(raw) => raw.form_id,
                    Err(_) => 0,
                };
                *image_unmapped_iclasses.entry(raw_iclass).or_insert(0) += 1;

                let entry_tally = global_tallies.entry(raw_iclass).or_insert_with(|| IclassCensus {
                    iclass_id: raw_iclass,
                    total_count: 0,
                    images_hit: BTreeSet::new(),
                    example_addr: addr,
                    example_bytes: concrete[..len.min(8)].to_vec(),
                });
                entry_tally.total_count += 1;
                entry_tally.images_hit.insert(file_name.clone());
            }

            addr = addr.wrapping_add(len as u64);
        }

        let mut ranked_image_unmapped: Vec<(u32, u64)> = image_unmapped_iclasses.into_iter().collect();
        ranked_image_unmapped.sort_by(|a, b| b.1.cmp(&a.1).then_with(|| a.0.cmp(&b.0)));
        let top3_unmapped: Vec<(u32, u64)> = ranked_image_unmapped.into_iter().take(3).collect();

        let unmapped_pct = if total_swept > 0 {
            100.0 * (unmapped_count as f64) / (total_swept as f64)
        } else {
            0.0
        };

        image_summaries.push(ImageSummary {
            name: file_name,
            total_swept,
            unmapped_count,
            unmapped_pct,
            top3_unmapped,
        });
    }

    // Sort images by unmapped percentage descending
    image_summaries.sort_by(|a, b| match b.unmapped_pct.partial_cmp(&a.unmapped_pct) {
        Some(ord) => ord.then_with(|| a.name.cmp(&b.name)),
        None => a.name.cmp(&b.name),
    });

    // Print per-image summary lines
    println!("=== PER-IMAGE INSTRUCTION-FORM CENSUS SUMMARY ===");
    for summary in &image_summaries {
        let top3_str = if summary.top3_unmapped.is_empty() {
            "none".to_string()
        } else {
            summary
                .top3_unmapped
                .iter()
                .map(|(id, count)| format!("{}({})", xed_iclass_name(*id), count))
                .collect::<Vec<_>>()
                .join(", ")
        };
        println!(
            "{:<35} | swept: {:>5} | unmapped: {:>5} ({:>5.1}%) | top unmapped: {}",
            summary.name, summary.total_swept, summary.unmapped_count, summary.unmapped_pct, top3_str
        );
    }

    // Rank top 30 unmapped iclasses by total occurrence count descending
    let mut ranked_iclasses: Vec<IclassCensus> = global_tallies.into_values().collect();
    ranked_iclasses.sort_by(|a, b| {
        b.total_count
            .cmp(&a.total_count)
            .then_with(|| a.iclass_id.cmp(&b.iclass_id))
    });

    let mut report = String::new();
    let total_swept_all: u64 = image_summaries.iter().map(|s| s.total_swept).sum();
    let total_unmapped_all: u64 = image_summaries.iter().map(|s| s.unmapped_count).sum();
    let overall_pct = if total_swept_all > 0 {
        100.0 * (total_unmapped_all as f64) / (total_swept_all as f64)
    } else {
        0.0
    };

    let total_images_swept = image_summaries.len();

    let _ = writeln!(report, "# Corpus Instruction-Form Coverage Census");
    let _ = writeln!(report);
    let _ = writeln!(report, "- **Total images discovered:** {}", total_processed);
    let _ = writeln!(report, "- **Images successfully swept:** {}", total_images_swept);
    let _ = writeln!(
        report,
        "- **Images skipped (unreadable / not PE64):** {}",
        total_skipped
    );
    let _ = writeln!(report, "- **Total instructions swept:** {}", total_swept_all);
    let _ = writeln!(
        report,
        "- **Total unmapped instructions:** {} ({:.2}%)",
        total_unmapped_all, overall_pct
    );
    let _ = writeln!(
        report,
        "- **Distinct unmapped XED iclasses:** {}",
        ranked_iclasses.len()
    );
    let _ = writeln!(report);
    let _ = writeln!(
        report,
        "## Top 30 Unmapped Instruction Classes (Ranked by Occurrence Count)"
    );
    let _ = writeln!(report);
    let _ = writeln!(
        report,
        "| Rank | XED IClass | IClass ID | Total Occurrences | Images Hit | Example Address | Example Bytes (hex) |"
    );
    let _ = writeln!(
        report,
        "|-----:|:-----------|----------:|------------------:|-----------:|:----------------|:---------------------|"
    );

    for (idx, item) in ranked_iclasses.iter().take(30).enumerate() {
        let hex_bytes = item
            .example_bytes
            .iter()
            .map(|b| format!("{b:02x}"))
            .collect::<Vec<_>>()
            .join(" ");
        let _ = writeln!(
            report,
            "| {:>4} | {:<20} | {:>9} | {:>17} | {:>6} / {:<4} | {:#018x} | `{}` |",
            idx + 1,
            xed_iclass_name(item.iclass_id),
            item.iclass_id,
            item.total_count,
            item.images_hit.len(),
            total_images_swept,
            item.example_addr,
            hex_bytes
        );
    }

    let _ = writeln!(report);
    let _ = writeln!(
        report,
        "## Per-Image Summary (Sorted by Unmapped Percentage Descending)"
    );
    let _ = writeln!(report);
    let _ = writeln!(
        report,
        "| Image | Total Swept | Unmapped | Unmapped % | Top 3 Unmapped IClasses |"
    );
    let _ = writeln!(
        report,
        "|:------|------------:|---------:|-----------:|:------------------------|"
    );

    for summary in &image_summaries {
        let top3_str = if summary.top3_unmapped.is_empty() {
            "none".to_string()
        } else {
            summary
                .top3_unmapped
                .iter()
                .map(|(id, count)| format!("{}({})", xed_iclass_name(*id), count))
                .collect::<Vec<_>>()
                .join(", ")
        };
        let _ = writeln!(
            report,
            "| {:<35} | {:>11} | {:>8} | {:>9.2}% | {} |",
            summary.name, summary.total_swept, summary.unmapped_count, summary.unmapped_pct, top3_str
        );
    }

    let _ = writeln!(report);
    let _ = writeln!(report, "### Per-Image Summary Lines");
    let _ = writeln!(report);
    for summary in &image_summaries {
        let top3_str = if summary.top3_unmapped.is_empty() {
            "none".to_string()
        } else {
            summary
                .top3_unmapped
                .iter()
                .map(|(id, count)| format!("{}({})", xed_iclass_name(*id), count))
                .collect::<Vec<_>>()
                .join(", ")
        };
        let _ = writeln!(
            report,
            "- `{}`: swept {}, unmapped {} ({:.1}%), top unmapped: {}",
            summary.name, summary.total_swept, summary.unmapped_count, summary.unmapped_pct, top3_str
        );
    }

    let report_path = "/tmp/corpus_form_gaps.md";
    let mut f = File::create(report_path)?;
    f.write_all(report.as_bytes())?;
    println!("Report written to {}", report_path);

    Ok(())
}
